import type { DashboardBlog } from "../types"

export const dashboardBlogs: DashboardBlog[] = [
  {
    id: "1",
    title: "Why We Chose Next.js for Every Client Project",
    slug: "why-we-chose-nextjs",
    category: "Next.js",
    status: "published",
    views: 3420,
    likes: 245,
    comments: 18,
    publishedAt: "2026-07-01",
  },
  {
    id: "2",
    title: "Designing Faster with shadcn/ui",
    slug: "designing-with-shadcn-ui",
    category: "Design",
    status: "published",
    views: 2110,
    likes: 198,
    comments: 12,
    publishedAt: "2026-06-18",
  },
  {
    id: "3",
    title: "GSAP vs Motion: When to Use Which",
    slug: "gsap-vs-motion",
    category: "Animation",
    status: "published",
    views: 1840,
    likes: 132,
    comments: 7,
    publishedAt: "2026-06-02",
  },
  {
    id: "4",
    title: "Structuring a Prisma Schema for a Growing Product",
    slug: "structuring-a-prisma-schema",
    category: "Backend",
    status: "published",
    views: 1220,
    likes: 88,
    comments: 4,
    publishedAt: "2026-05-20",
  },
  {
    id: "5",
    title: "Why We Organize Next.js Projects by Feature",
    slug: "feature-based-folder-structure",
    category: "Architecture",
    status: "draft",
    views: 0,
    likes: 0,
    comments: 0,
    publishedAt: "2026-05-05",
  },
  {
    id: "6",
    title: "Adding AI Features to an Existing App Without a Rewrite",
    slug: "adding-ai-features-to-existing-apps",
    category: "AI",
    status: "draft",
    views: 0,
    likes: 0,
    comments: 0,
    publishedAt: "2026-04-14",
  },
]
