import type { DashboardProject } from "../types"

export const dashboardProjects: DashboardProject[] = [
  {
    id: "1",
    title: "Nova Ecommerce",
    slug: "nova-ecommerce",
    description: "A full-featured online store with cart, checkout, and an admin panel.",
    clientName: "Nova Retail",
    budget: "$12,000",
    status: "published",
    views: 1420,
    tags: ["Next.js", "Stripe", "PostgreSQL"],
    completedAt: "2026-06-01",
  },
  {
    id: "2",
    title: "Fintrack",
    slug: "fintrack",
    description: "A personal finance dashboard for tracking spending, budgets, and savings goals.",
    clientName: "Fintrack Inc.",
    budget: "$8,500",
    status: "published",
    views: 980,
    tags: ["React", "Node.js", "MongoDB"],
    completedAt: "2026-05-10",
  },
  {
    id: "3",
    title: "Healthbridge",
    slug: "healthbridge",
    description: "A telemedicine platform connecting patients with doctors for online consultations.",
    clientName: "Healthbridge Org",
    budget: "$15,000",
    status: "published",
    views: 2110,
    tags: ["Next.js", "TypeScript", "WebRTC"],
    completedAt: "2026-04-22",
  },
  {
    id: "4",
    title: "Cargoo Logistics",
    slug: "cargoo-logistics",
    description: "A fleet management system with live tracking and route optimization.",
    clientName: "Cargoo Global",
    budget: "$24,000",
    status: "published",
    views: 650,
    tags: ["React", "Express", "PostgreSQL"],
    completedAt: "2026-03-15",
  },
  {
    id: "5",
    title: "EduSpark LMS",
    slug: "eduspark-lms",
    description: "An online learning platform with courses, quizzes, and progress tracking.",
    clientName: "EduSpark",
    budget: "$18,000",
    status: "draft",
    views: 0,
    tags: ["Next.js", "Prisma", "PostgreSQL"],
    completedAt: "2026-02-08",
  },
  {
    id: "6",
    title: "Realty Hub",
    slug: "realty-hub",
    description: "A real estate listing platform with search filters and virtual tours.",
    clientName: "Realty Hub Ltd",
    budget: "$9,200",
    status: "draft",
    views: 0,
    tags: ["Next.js", "Tailwind CSS", "MongoDB"],
    completedAt: "2026-01-20",
  },
]
