import type { Blog } from "../types/blog.types"

export const blogs: Blog[] = [
  {
    id: "1",
    slug: "why-we-chose-nextjs",
    title: "Why We Chose Next.js for Every Client Project",
    excerpt: "A look at the reasons Next.js is our default starting point for new builds.",
    content: "A look at the reasons Next.js is our default starting point for new builds. From file-based routing to built-in image optimization and server components, it removes a lot of setup work so we can focus on the actual product from day one.",
    coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80",
    tags: ["Next.js"],
    readTime: 4,
    featured: true,
    publishedAt: "2026-07-01",
  },
  {
    id: "2",
    slug: "designing-with-shadcn-ui",
    title: "Designing Faster with shadcn/ui",
    excerpt: "How owning your component code instead of installing a UI library changes how you build.",
    content: "How owning your component code instead of installing a UI library changes how you build. Because components are copied into your project rather than imported from a package, every button and dialog can be customized freely without fighting an external API.",
    coverImage: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80",
    tags: ["Design"],
    readTime: 5,
    featured: true,
    publishedAt: "2026-06-18",
  },
  {
    id: "3",
    slug: "gsap-vs-motion",
    title: "GSAP vs Motion: When to Use Which",
    excerpt: "Two animation libraries, two different jobs — here's how we split them on client projects.",
    content: "Two animation libraries, two different jobs — here's how we split them on client projects. Motion handles anything tied to component state, while GSAP takes over for timeline-heavy scroll sequences.",
    coverImage: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
    tags: ["Animation"],
    readTime: 6,
    featured: true,
    publishedAt: "2026-06-02",
  },
  {
    id: "4",
    slug: "structuring-a-prisma-schema",
    title: "Structuring a Prisma Schema for a Growing Product",
    excerpt: "Lessons from modeling a database that had to support features we hadn't built yet.",
    content: "Lessons from modeling a database that had to support features we hadn't built yet. Keeping relations explicit and naming consistent saved hours of rework as new features were added.",
    coverImage: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=800&q=80",
    tags: ["Backend"],
    readTime: 7,
    featured: false,
    publishedAt: "2026-05-20",
  },
  {
    id: "5",
    slug: "feature-based-folder-structure",
    title: "Why We Organize Next.js Projects by Feature",
    excerpt: "Keeping the app router for routing only, and everything else grouped by feature.",
    content: "Keeping the app router for routing only, and everything else grouped by feature. It keeps related components, hooks, and types together, so a new developer can find everything about one feature in one place.",
    coverImage: "https://images.unsplash.com/photo-1605379399642-870262d3d051?auto=format&fit=crop&w=800&q=80",
    tags: ["Architecture"],
    readTime: 5,
    featured: false,
    publishedAt: "2026-05-05",
  },
  {
    id: "6",
    slug: "adding-ai-features-to-existing-apps",
    title: "Adding AI Features to an Existing App Without a Rewrite",
    excerpt: "How we bolt on chat and search features to products that weren't built with AI in mind.",
    content: "How we bolt on chat and search features to products that weren't built with AI in mind. Most of the time it comes down to one new API route and a small UI component, not a rewrite.",
    coverImage: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
    tags: ["AI"],
    readTime: 6,
    featured: false,
    publishedAt: "2026-04-14",
  },
]
