import type { Project } from "../types/project.types"

export const projects: Project[] = [
  {
    id: "1",
    slug: "nova-ecommerce",
    title: "Nova Ecommerce",
    description: "A full-featured online store with cart, checkout, and an admin panel.",
    coverImage: "https://images.unsplash.com/photo-1557821552-17105176677c?auto=format&fit=crop&w=800&q=80",
    category: "E-commerce",
    tags: ["Next.js", "Stripe", "PostgreSQL"],
    liveUrl: "https://example.com/nova-ecommerce",
    featured: true,
    completedAt: "2026-06-01",
  },
  {
    id: "2",
    slug: "fintrack",
    title: "Fintrack",
    description: "A personal finance dashboard for tracking spending, budgets, and savings goals.",
    coverImage: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=800&q=80",
    category: "SaaS",
    tags: ["React", "Node.js", "MongoDB"],
    liveUrl: "https://example.com/fintrack",
    featured: true,
    completedAt: "2026-05-10",
  },
  {
    id: "3",
    slug: "healthbridge",
    title: "Healthbridge",
    description: "A telemedicine platform connecting patients with doctors for online consultations.",
    coverImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80",
    category: "Web App",
    tags: ["Next.js", "TypeScript", "WebRTC"],
    liveUrl: "https://example.com/healthbridge",
    featured: true,
    completedAt: "2026-04-22",
  },
  {
    id: "4",
    slug: "cargoo-logistics",
    title: "Cargoo Logistics",
    description: "A fleet management system with live tracking and route optimization.",
    coverImage: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80",
    category: "SaaS",
    tags: ["React", "Express", "PostgreSQL"],
    liveUrl: "https://example.com/cargoo-logistics",
    featured: false,
    completedAt: "2026-03-15",
  },
  {
    id: "5",
    slug: "eduspark-lms",
    title: "EduSpark LMS",
    description: "An online learning platform with courses, quizzes, and progress tracking.",
    coverImage: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80",
    category: "Web App",
    tags: ["Next.js", "Prisma", "PostgreSQL"],
    liveUrl: "https://example.com/eduspark-lms",
    featured: false,
    completedAt: "2026-02-08",
  },
  {
    id: "6",
    slug: "realty-hub",
    title: "Realty Hub",
    description: "A real estate listing platform with search filters and virtual tours.",
    coverImage: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80",
    category: "Web App",
    tags: ["Next.js", "Tailwind CSS", "MongoDB"],
    liveUrl: "https://example.com/realty-hub",
    featured: false,
    completedAt: "2026-01-20",
  },
]
